// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu-DSFI38bioNPu9e8UWqwDJVOA-tHtfU',
    appId: '1:981426707986:web:16d6ec27e0ac434c2942cb',
    messagingSenderId: '981426707986',
    projectId: 'hammad-fa399',
    authDomain: 'hammad-fa399.firebaseapp.com',
    storageBucket: 'hammad-fa399.firebasestorage.app',
    measurementId: 'G-69VDV0T5TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeJF8YzAdZMNLcGeLXip_lAwiTdHl6Lgs',
    appId: '1:981426707986:android:557630893f3e3ba82942cb',
    messagingSenderId: '981426707986',
    projectId: 'hammad-fa399',
    storageBucket: 'hammad-fa399.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu-DSFI38bioNPu9e8UWqwDJVOA-tHtfU',
    appId: '1:981426707986:web:7c918ff4f5cbbbab2942cb',
    messagingSenderId: '981426707986',
    projectId: 'hammad-fa399',
    authDomain: 'hammad-fa399.firebaseapp.com',
    storageBucket: 'hammad-fa399.firebasestorage.app',
    measurementId: 'G-P2QLPBL18T',
  );
}
